name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Check for updates
      id: updates
      run: |
        # Check for outdated packages
        npm outdated --json > outdated.json || true
        
        if [ -s outdated.json ]; then
          echo "has_updates=true" >> $GITHUB_OUTPUT
          echo "📦 Found outdated dependencies"
          cat outdated.json
        else
          echo "has_updates=false" >> $GITHUB_OUTPUT
          echo "✅ All dependencies are up to date"
        fi

    - name: Update dependencies
      if: steps.updates.outputs.has_updates == 'true'
      run: |
        # Update patch and minor versions
        npm update
        
        # Install latest compatible versions
        npm install

    - name: Run tests after update
      if: steps.updates.outputs.has_updates == 'true'
      run: |
        npm run type-check
        npm run lint
        npm test
      env:
        NODE_OPTIONS: --max_old_space_size=4096

    - name: Create Pull Request
      if: steps.updates.outputs.has_updates == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: '🔄 Automated dependency updates'
        body: |
          ## 📦 Dependency Updates
          
          This PR contains automated dependency updates.
          
          ### Changes
          - Updated npm dependencies to latest compatible versions
          - All tests pass after updates
          - No breaking changes detected
          
          ### Testing
          - ✅ Type checking passed
          - ✅ Linting passed  
          - ✅ Jest tests passed
          
          ### Review Notes
          Please review the changes and ensure:
          - [ ] All tests continue to pass
          - [ ] No unexpected behavior changes
          - [ ] Dependencies are compatible with current Node.js version
          
          **Auto-generated by GitHub Actions**
        branch: dependencies/auto-update
        delete-branch: true
        labels: |
          dependencies
          automated

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit
      run: |
        # Run npm audit and capture results
        npm audit --audit-level=moderate --json > audit-results.json || true
        
        # Check if there are any vulnerabilities
        if [ -s audit-results.json ]; then
          VULNERABILITIES=$(cat audit-results.json | jq '.metadata.vulnerabilities | to_entries | map(select(.value > 0)) | length')
          
          if [ "$VULNERABILITIES" -gt 0 ]; then
            echo "⚠️ Security vulnerabilities found!"
            npm audit --audit-level=moderate
            
            # Try to fix automatically
            npm audit fix --force || true
            
            echo "has_security_issues=true" >> $GITHUB_OUTPUT
          else
            echo "✅ No security vulnerabilities found"
            echo "has_security_issues=false" >> $GITHUB_OUTPUT
          fi
        fi

    - name: Create security fix PR
      if: env.has_security_issues == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'security: fix npm audit vulnerabilities'
        title: '🔒 Security: Fix npm audit vulnerabilities'
        body: |
          ## 🔒 Security Vulnerability Fixes
          
          This PR contains automated security fixes for npm audit vulnerabilities.
          
          ### Changes
          - Applied `npm audit fix` to resolve security issues
          - Updated vulnerable dependencies to secure versions
          
          ### Security Summary
          See the workflow logs for detailed vulnerability information.
          
          ### Testing Required
          - [ ] Verify all tests still pass
          - [ ] Check for any breaking changes
          - [ ] Ensure application functionality is intact
          
          **⚠️ IMPORTANT**: This PR contains security fixes and should be reviewed and merged promptly.
          
          **Auto-generated by GitHub Actions Security Audit**
        branch: security/auto-fix
        delete-branch: true
        labels: |
          security
          automated
          high-priority